### ISSUE TITLE
電源のつなぎ方

### ISSUE THREAD

**Issue by marubashi11** [CIR-KIT/raspi_mouse_pkg#1]
バッテリの付属品がありましたが, 充電器が見当たりません. どうすうればいいですか.

**Comment by yasu80** [comment]
見たところ, 11.1V 1A モードで
近藤科学のLi-Po用バランスチャージャが使えそうです.
Ni-MH(ニッスイ)用とかを使わないように気をつけてください. 発火します.
![6596967679928](https://user-images.githubusercontent.com/16016288/29705768-78ef6b2c-89ba-11e7-8204-9bcff7f68d20.jpg)

**Comment by marubashi11** [comment]
わかりましたやってみます

**Comment by yasu80** [comment]
なにかわからないことがあったらどうぞ

**Comment by yasu80** [comment]
wikiにまとめまし
