### ISSUE TITLE
RasPi3 + Ubuntuがネットに繋がらなくなる話

### ISSUE THREAD

**Issue by yasu80** [CIR-KIT/raspi_mouse_pkg#2]
ひとばんじゅう探したら出てきましたとさ...

新しくドライバ入れ直すのが早いそうです。そうしますか

**Comment by yasu80** [comment]
猛烈に眠いので後で対応します

**Comment by yasu80** [comment]
実のところ学内のネットワークはDNS周りとローミングとでちょっとアレなのでまだ一苦労あるかも？
ただ、こっちの構築のところで何か間抜けなミスしてる可能性が大なのでまだ保留

**Comment by forno** [comment]
探したら出てきたというのならURL貼っとくのです。

**Comment by yasu80** [comment]
やるべき操作が乗っていますが

https://github.com/ryuichiueda/raspimouse_book_info/issues/1
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=141834#p1152584

適用後も未だに解決しません. まず持ってオープンWifiにオンボードデバイスからwpa_supplicantで接続することができません.

wlan0 において ifup ifdown を実行できません. 多分さっきの話とは別?

**Comment by yasu80** [comment]
wlan0はパッチ当てたうえで記述を
http://404-notfound.jp/archives/374#more-374
に準じた結果成功
ca-certに失敗しているのだがよくわからん

**Comment by yasu80** [comment]
wikiに今回の知見まとめておきます
