### ISSUE TITLE
Wiki 整理

### ISSUE THREAD

**Issue by forno** [CIR-KIT/raspi_mouse_pkg#4]
WikiのHomeに全部突っ込んでて読みづらいので
Homeにdescriptionを書いてリンクを貼りたい

**Comment by yasu80** [comment]
編集中のようなので静観

**Comment by forno** [comment]
ひとまずざっくり編集しました。

**Comment by yasu80** [comment]
大体いいと思います.
記述が増えたら(暇のあるときに)定期的に整理していきたいです

**Comment by yasu80** [comment]
思いついたんですけど,

<hr>

もと記載されていたwikiの記述がこれこれだったとして

<hr>

当然更新され,

<hr>

もと記載されていたwikiの記述がこれこれだったとして
~パッチ当てたよ！ `hogehoge`~
非推奨メソッドです `bokoboko`
※bokobokoは不安定なのでhogehogeで

<hr>

ってなってくると割と悪夢なので

<hr>

もと記載されていたwikiの記述がこれこれだったとして(yasu1)
↑ パッチ当てたよ！ `hogehoge` (yasu2)
↑ 非推奨メソッドです `bokoboko` (yasu3)
↑ この環境では不安定なので bokoboko はやめて hogehogeで(yasu3)

<hr>

てな感じに編集者名つけていくルールにしたいです(小声)

**Comment by forno** [comment]
ぶっちゃけ使ってるもの以外の過去の情報いらないんでまるまるいらないものは残さす削除してくださいな。
的な。

**Comment by forno** [comment]
リビジョンは残ってるので。

**Comment by yasu80** [comment]
了解です,
