### ISSUE TITLE
トラブルシューティング:デバイスドライバ周りの情報

### ISSUE THREAD

**Issue by yasu80** [CIR-KIT/raspi_mouse_pkg#5]
Ubuntu 16.04 Server armhf版に先んじてインストールした

https://github.com/citueda/RaspberryPiMouse

にある(master)ドライバは稼働していたんですけど, Wirelessが稼働しなかったため, (iwconfig上に上がってこない. interfacesとかは正当. eth0は稼働.)

https://github.com/ryuichiueda/raspimouse_book_ubuntu_init/blob/master/after_os_install.bash

↑を実行の後に変化なかったため, 手動にてドライバを更新

 https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm/brcmfmac43430-sdio.bin
 https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm/brcmfmac43430-sdio.txt

したところデバイスツリーが壊れてブート不可能になりましたにゃんにゃんにゃん

<hr>

https://github.com/ryuichiueda/raspimouse_book_info
ここにあった(ある)んですけれど

> 重要な情報
> デバイスドライバにバグがありました。まだマスタにはマージしていませんが、カーネルパニックが頻発している場合はこちらのブランチを試してみてください。

実際検証不足ですが, これ以上時間をかけるのも得策ではないので再インストールかけます.

パッチ当ててから手動でのドライバ更新までしばらく運用していましたし, デバイスツリーが破損する理由について思い当たらないのですが, ともかく報告だけ.

当方カーネル周辺の挙動, 不勉強のため解決困難です. (しばらく進展無かったら閉じます)

**Comment by forno** [comment]
しばらく経ちましたがいかがでしょうか

**Comment by yasu80** [comment]
無理です()
一旦クローズしたい.
