### ISSUE TITLE
Wikiが理解できない

### ISSUE THREAD

**Issue by forno** [CIR-KIT/raspi_mouse_pkg#6]
書き込み確認してたら（私はコミットを全て追っているのでまだわかる方ですが）
打ち消し線あり、正しそうな文章の最後に上手く行きません宣言あり、結局正しい方法まだ見つかってないじゃんf*ckありで見づらいので、

やっては行けないことを残したい気持ちもわかるので、折衷案としてやってはいけないリストページを作成して、そちらへ必要なタイミングでリンクを貼る形式にしてほしいなーと。

具体例としてはWikiの[インストール](https://github.com/CIR-KIT/raspi_mouse_pkg/wiki/%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB)

> ~Wi-fiがつながらなくて死ぬほど不便するので, 
https://github.com/ryuichiueda/raspimouse_book_ubuntu_init/blob/master/after_os_install.bash
にてパッチを当てます。(でもすぐにはつながらないはずですから, 下の設定をしないんとストレス死待ったなしです~
> これをやると後々ビルドが通らなくなりますし, しかも最初にやらないと意味がない(Update停止処理なので)やめてください.

この文章は

***
正しい方法はいまだ不明.
今までの挑戦
- brcmの書き換え (挑戦中)
- [パッチを当てて設定を行う (ビルドできなくなる)](やってはいけないリスト#インストール-パッチを当てて設定を行う)

## brcmの書き換え（挑戦中）
作業ログは[[ログ]]参照。
現在、再起動すると起動しなくなる問題あり。

以下説明
***

的になってると見やすいかと思います。
見やすい工夫をお願い申し上げます。

**Comment by yasu80** [comment]
了解です.

打開のめどが立たないので,  Raspi Mouse は当分いじりません. 凍結します
